# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_output_repo {c:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {{C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Desktop/TestIO.dat}}
read_verilog -library xil_defaultlib -sv {
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/ALU.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/ALUcontrol.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/new/CLA32.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/new/CLA4.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/new/CLA4_Marked.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/sources_1/new/CLK_DIV.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/DataPath.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/DataRegister.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/Decoder.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/Extender.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/sources_1/imports/new/IO.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/InstructionRegister.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/MIPS.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/MUX2X1.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/MUX2X32.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/MUX2X5.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/MUX2X6.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/new/MUX3X32_Data.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/new/MUX4X32_Data.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/new/MUX4X32_PC.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/MUX6X32.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/sources_1/imports/new/MUX7SEG.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/new/MemoryDecoder_NEXYS_A7_100T.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/new/Memory_IO.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/ProgramCounter.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/RegisterFile.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/imports/Multi Cycle MIPS Processor.srcs/sources_1/new/Shifter.sv}
  {C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/sources_1/new/Top_IO_NEXYS_A7_100T.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/constrs_1/imports/Desktop/Nexys-A7-100T-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Half Blood Prince/Desktop/Multi-Cycle-MIPS-Basic-IO2/Multi-Cycle-MIPS-Basic-IO.srcs/constrs_1/imports/Desktop/Nexys-A7-100T-Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top_IO_NEXYS_A7_100T -part xc7a100tcsg324-1 -gated_clock_conversion on -fsm_extraction off -keep_equivalent_registers -resource_sharing off -no_lc -no_srlextract


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_IO_NEXYS_A7_100T.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_IO_NEXYS_A7_100T_utilization_synth.rpt -pb Top_IO_NEXYS_A7_100T_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
