@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Jun 02 12:23:13 +0800 2024
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim test_Top_IO_behav -key {Behavioral:sim_1:Functional:test_Top_IO} -tclbatch test_Top_IO.tcl -view C:/Users/Half Blood Prince/Desktop/MIPS_BasicIO/test_Top_behav.wcfg -view C:/Users/Half Blood Prince/Desktop/MIPS_BasicIO/test_Top_IO_behav.wcfg -log simulate.log"
call xsim  test_Top_IO_behav -key {Behavioral:sim_1:Functional:test_Top_IO} -tclbatch test_Top_IO.tcl -view C:/Users/Half Blood Prince/Desktop/MIPS_BasicIO/test_Top_behav.wcfg -view C:/Users/Half Blood Prince/Desktop/MIPS_BasicIO/test_Top_IO_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
